name: Inspect boot image

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check boot.img.zip
        run: |
          file boot.img.zip
          ls -lh boot.img.zip
          xxd -l 32 boot.img.zip
